spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          - id: changgou_goods_route
            uri: lb://goods
            predicates:
             #- Host=cloud.itheima.com**
            # - Path=/api/brand/**
            - Path=/api/goods/**
            filters:
            - StripPrefix=1
             #- PrefixPath=/brand
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 1 #令牌桶总容量
          - id: changgou_user_route
            uri: lb://user
            predicates:
            - Path=/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**,/api/user/**
            filters:
            - StripPrefix=1


server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
