server:
  port: 18083

spring:
  application:
    name: canal

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
canal:
  client:
    instances:
      example:
        host: 192.168.89.111
        port: 11111


